# Generated by Django 5.1.7 on 2025-03-13 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('geracao', models.PositiveIntegerField()),
                ('tipo', models.CharField(max_length=20)),
                ('habilidade', models.TextField()),
            ],
        ),
    ]
